### ISSUE TITLE
installer failure

### ISSUE THREAD

**Issue by lsmith77** [redkite-labs/RedKiteCmsSandbox#2]
```
[RuntimeException]

  RedKite CMS requires an existing bundle to work with. You enter as working bundle the following: Liip\WebSiteBundle but, the bundle is not enable in AppKernel.php file. Please add t
  he bundle or enable it ther run the script again.
```

Would be a good idea to mention in the docs to use the default company name I guess or are there plans to automatically adjust the Bundle name?

**Comment by redkite-labs** [comment]
Hi Lukas,
thank you very much for your question, I suppose you are talking about this part of the docs, don't you? http://redkite-labs.com/how-to-install-redkite-cms#the-deploy-bundle

That's a great suggestion, so I'll add a note to provide that information!

**Comment by redkite-labs** [comment]
Hi,
for me these closes the issue:
http://redkite-labs.com/download-redkite-cms-sandbox#installing-from-the-console
http://redkite-labs.com/how-to-install-redkite-cms#the-deploy-bundle
