### ISSUE TITLE
web interface installer "syntax error near unexpected token"

### ISSUE THREAD

**Issue by rene1983** [redkite-labs/RedKiteCmsSandbox#3]
I've uploaded all files to my shared hosting service. File permissions and db credentials have been double checked yet I get this issue after around 20 seconds after clicking "install" in the web interface installer (I replaced real values for privacy):

sh: -c: line 0: syntax error near unexpected token `(' sh: -c: line 0:`'/usr/bin/php' /home/ridmx/public_html/app/console redkitecms:configure --no-interaction --company={{CompanyNameNoSpaces}} --bundle={{BundleNameNoSpaceswithUnderscores}} --host=localhost --database={{DBName}} --user={{DBUserwithUnderscores}} --driver=mysql --port=3306 --password={{15charsStrong password with numbers , "%" and ")" }} --website-url=http://www.{{Domain no \ sufix}}'
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

**Comment by redkite-labs** [comment]
Hello,
have you download the patch for the Beta 3 release? http://redkite-labs.com/download-get-and-go-redkite-cms-sandbox#mysql-users-patch If that not solves, please run that command in the dev environment adding the --env=app_dev switch and post the output.

Let me know if you solve.

Thanks
