### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by rejsmont** [redkite-labs/RedKiteCmsSandbox#4]
Hi,

it seems your CMS is using extensive writes outside of cache, logs and web (like in app/config or inside the WebSiteBundle). Apart from the fact that writing into bundles can break VCS and writing files in configs might pose a security thread, this is completely omitted from README. Could you please update the README so that is clearly shows which directories should be web server-writable?

Best,

Radek

**Comment by janxin** [comment]
Sorry for long delay. Thank you very much for reporting back
