### ISSUE TITLE
Remove Doctrine as a requirement

### ISSUE THREAD

**Issue by boekkooi** [redkite-labs/RedKiteCmsSandbox#5]
Remove `doctrine/orm` and `doctrine/doctrine-bundle` from the composer.json and config files since this is not a requirement for running RedKiteCms.

**Comment by janxin** [comment]
Though RedKite CMS works with Propel, I prefer to leave the Doctrine requirement and provide the Sandbox with these packages because the sandbox must be a Symfony2 standard edition powered by RedKite.
