### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by hypervalley** [redkite-labs/RedKiteCmsSandbox#6]
Hi, I've found 2 problems installing RedKiteCmsSandbox:
1- Install via console requires existence of a bundle. This mustn't use "Bundle" folder.
app/console generate:bundle
Cause error in app/console redkitecms:configure:
  Bundle namespace:  RedKiteLabs/Bundle/WebSiteBundle
  Based on the namespace, we suggest RedKiteLabasWebSiteBundle
Don't cause error in app/console redkitecms:configure:
  Bundle namespace:  RedKiteLabs/WebSiteBundle
  Based on the namespace, we suggest RedKiteLabasWebSiteBundle

2- Install via console and via web interfaxe causes error in website url. I'm trying to install in a cloud server.
website url:  http://domain.net/projects/dev/Symfony_rksb/
Error: Website url must start with "http://" and must end with "/" 

I suggest you adjust the tutorial in https://github.com/redkite-labs/RedKiteCmsSandbox:
  app/console rekitecms:configure -> app/console redkitecms:configure
  app/console rekitecms:install --env=rkcms -> app/console redkitecms:install --env=rkcms
  http://localhost/app_dev.php/install -> http://localhost/web/app_dev.php/install (?)
  http://domain.com/web/app_dev.php/install (Add.)

Thank's

**Comment by janxin** [comment]
Hi,
about the point 2 the mandatory domain url is the url that defined the website, let's say http://mysite.domain.net, and must point the sandbox web folder which should be http://domain.net/projects/dev/Symfony_rksb/web in your example. The "localhost" comment has sense and I will fix it.

Let me investigate on the issue reported at point 1.

**Comment by janxin** [comment]
following commit fixes the issue. https://github.com/redkite-labs/InstallerBundle/commit/7e9a79285ba864716df815eb9035102121cb454d

Thanks!
