### ISSUE TITLE
Unable to execute SELECT statement

### ISSUE THREAD

**Issue by khusseini** [redkite-labs/RedKiteCmsSandbox#8]
After logging in for the first time in the backend I am getting the error:
Unable to execute SELECT statement [SELECT [id], [role] FROM [al_role] WHERE [id] = :p0] [wrapped: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[id], [role] FROM [al_role] WHERE [id] = 2' at line 1]

How can I resolve this?

**Comment by khusseini** [comment]
Here is the complete exception

```
Uncaught PHP Exception PropelException: "Unable to execute SELECT statement [SELECT [id], [role] FROM [al_role] WHERE [id] = :p0] [wrapped: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[id], [role] FROM [al_role] WHERE [id] = 2' at line 1]" at /var/www2/sfCmsSandbox/vendor/redkite-cms/redkite-cms-bundle/RedKiteLabs/RedKiteCmsBundle/Model/om/BaseAlRoleQuery.php line 154 
```

**Comment by janxin** [comment]
It looks like something goes wrong with the database configuration: could you run the php app/console propel:model:build --env=rkcms command and post the output here?

**Comment by khusseini** [comment]
Hi there,
Though I already moved on to the next CMS to test here is the output of the command

```
>>      RedKiteCmsBundle    Generated model classes from schema.xml
```

**Comment by janxin** [comment]
mmh...could you try to run the php app/console redkitecms:install --env=rkcms command and post the output here?

In the meantime, if you just need to test, you could try the demo http://redkite-labs.com/redkite-cms-demo
