### ISSUE TITLE
Errors when install cms

### ISSUE THREAD

**Issue by ivan24** [redkite-labs/RedKiteCmsSandbox#9]
I downloaded cms with vendors from http://redkite-labs.com/download-redkite-cms-built-on-top-of-symfony2-and-twitter-bootstrap-frameworks.
Then I open http://localhost/install and provide all information i get error:
 [Propel] Error
An error has occured during the "om" task process. To get more details, run the command with the "--verbose" option.

**Comment by janxin** [comment]
This repository is deprecated. Moved issue there: https://github.com/redkite-labs/RedKiteCms/issues/63
